---
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - build/*
  - dist/*
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/react-in-jsx-scope: 'off'
settings:
  react:
    version: detect # React version. "detect" automatically picks the version you have installed.
  componentWrapperFunctions: []
  # The name of any function used to wrap components, e.g. Mobx `observer` function. If this isn't set, components wrapped by these functions will be skipped.
  formComponents: [] # Components used as alternatives to <form> for forms, eg. <Form endpoint={ url } />
  linkComponents: [] # Components used as alternatives to <a> for linking, eg. <Link to={ url } />
