export const columns = [
  'Macro Serviço',
  'Macrocélula',
  'Célula',
  'Complexidade',
  'Fator de Ponderação',
  'Atividade',
  'Coordenação_Gestora',
  'Esforço (Horas)',
  'Simulta-neidade',
  'Cobertura Início',
  'Cobertura Fim',
  'Dias uteis',
  'Dias não uteis',
  'ALTERADO/RETIFICADO?',
  'Total de UST',
]

export const month1 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'CENTRAL DE ATENDIMENTO E MONITORAÇÃO',
  'GERENCIAMENTO DA INFRA DE MONITORAÇÃO DATACENTER',
  'MEDIA',
  1.84,
  'Propor, Implementar, Manter, Atualizar, Validar, Documentar melhorias nos processos e ferramentas de gestão de serviços de TI preconizados pelo ITIL (implementados e/ou a implementar). a. Promover ações para aumento da eficiência e eficácia dos processos e execuções sob sua responsabilidade; b. Apresentar plano de ação de recuperação de qualidade; c. Adequar o funcionamento dos Hardware, Software, Ferramentas e Aplicações visando à compatibilidade e facilidade na utilização; d. export construir, manter, atualizar e customizar interfaces, consoles, filtros, macros, script e painéis dentre outros meios, que permitam o acompanhamento e gerenciamento dos serviços de TI prestados pela CAIXA; e. Participar/ atuar na definição dos critérios de acionamento e escalonamento de incidentes, serviços, problemas, mudanças e configurações.',
  'COORDENAÇÃO2',
  8,
  1,
  '09:00',
  '18:00',
  22,
  0,
  '',
  323.84,
]

export const month2 = [
  'Suporte a Gestão de Monitoramento a incidentes, problemas e mudanças',
  'CENTRAL DE ATENDIMENTO E MONITORAÇÃO',
  'GERENCIAMENTO DA INFRA DE MONITORAÇÃO DATACENTER',
  'BAIXA',
  1,
  '1. Realizar procedimentos de monitoração, acionamento e recuperação dos serviços conforme padrão e prazos definidos pela CAIXA. (DIURNO / NOTURNO/MADRUGADA/FINAL DE SEMANA) a. Acompanhar disponibilidade do ambiente computacional; b. Atuar de forma preventiva e proativa na detecção de falhas e solucionar ocorrências com tempestividade, visando à disponibilidade dos IC administrados; c. Comunicar tempestivamente à equipe CAIXA, quaisquer incidentes detectados, eventos, situações anormais identificadas e problemas relacionados a hardware, software e aplicação, bem como quaisquer dificuldades/problemas que venham sendo enfrentados com as unidades internas ou externas; d. Detectar/ Acionar/ Registrar incidentes conforme padrão definido pela CAIXA; e. Resolver incidentes de todos os servidores, produtos, bancos de dados, componentes, serviços ou sistemas, em quaisquer ambientes Computacionais da CAIXA sob sua responsabilidade, interagindo com uma ou mais equipes técnicas, promovendo o restabelecimento desses serviços e documentando a solução de contorno; f. Acompanhar resolução de incidentes pendentes para que as medidas corretivas sejam providenciadas tempestivamente; g. Apresentar controle de ocorrências e da disponibilidade dos ambientes computacionais da CAIXA; h. Atuar em conjunto com outras equipes no planejamento da instalação/ implantação/ alteração na infraestrutura de TI da CAIXA, realizando testes, avaliações e liberações referentes à sua área de atuação; i. Executar e documentar tarefas em ambiente sob sua responsabilidade conforme padrão e prazos definidos pela CAIXA; j. Abrir/ Registrar/ Acompanhar chamados técnicos junto às unidades internas e externas e/ou empresas, quando devidamente autorizado pela CAIXA, acompanhando todas as ações corretivas e as manutenções até o efetivo restabelecimento do serviço/ software/ hardware. k. Realizar atendimento de primeiro nível de Incidentes e Serviços;',
  'COORDENAÇÃO2',
  24,
  2,
  '07:00',
  '23:59',
  22,
  8,
  '',
  1440,
]

export const month3 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'CENTRAL DE ATENDIMENTO E MONITORAÇÃO',
  'GERENCIAMENTO DA INFRA DE MONITORAÇÃO DATACENTER',
  'BAIXA',
  1,
  '2. Realizar atendimento de Incidentes, Serviços, Mudanças ou Tarefas conforme padrão e prazos definido pela CAIXA. (DIUNO/NOTURNO) a. Abrir, Validar, Tratar, Registrar, Encaminhar, Fechar registros de Incidentes, Serviços, Mudanças, Problemas ou Tarefas; b. Efetuar o gerenciamento dos Incidentes, Serviços, Mudanças, Problemas, conforme as melhores práticas preconizadas pelo ITIL; c. Atuar como ponto focal, coletar/enviar informações e acompanhar a solução dos Incidentes, Serviços, Mudanças, Problemas ou Tarefas junto ao responsável pelo serviço, sistema ou rotina, seja de área interna ou externa à sua unidade na ferramenta de gestão.; d. Atender as demandas provenientes dos clientes externos ou internos à, nos canais definidos pela CAIXA; e. Promover ações para a manutenção da conformidade dos processos sob sua responsabilidade; f. Realizar atendimento de primeiro nível nos processos sob sua responsabilidade; g. Executar as boas práticas da funcionalidade de Central de Serviços (SERVICE DESK) alinhadas aos processos de gerenciamento dos demais processos preconizados pelo ITIL. h. Atuar em todo o ciclo de vida da mudança, internalizar, evoluir e fechar o registro com o resultado da implantação, sendo o ponto focal entre as equipes técnicas. i. Acionar os envolvidos na mudança para resolução de dúvidas e validação das demandas. h. Garantir o cumprimento do prazo de atendimento das mudanças, i) Garantir a execução, a análise, o diagnóstico, a otimização, o acompanhamento e a programação de rotinas de processamento on-line, batch, e de scripts manuais ou automatizados das rotinas e sistemas da unidade, em periodicidades diversas, ou ainda, garantir a execução e o acompanhamento das tarefas de infraestrutura. j) Criar, manter, implementar e documentar rotinas de apoio aos processos em produção. l) Zelar pela disponibilidade das bases de dados nos horários previstos, e pelos horários e prazos programados das tarefas, rotinas, scripts e bases de dados, m) Atender e solucionar incidentes relativos à execução e programação de rotinas, scripts, tarefas, disponibilização de bases, acionando e acompanhando as equipes técnicas internas ou o fornecedor/fabricante quando necessário, n) Atender requisições de serviços relativos a execução, o acompanhamento, a análise, o diagnóstico, a otimização e a programação de rotinas de processamento on-line, batch e de scripts, em periodicidades diversas, ou ainda, garantir a execução e o acompanhamento de tarefas de infraestrutura, o) Realizar e manter o inventário/CMDB dos sistemas, rotinas ou tarefas da unidade, e manter dados atualizados acerca da execução das demandas da unidade ',
  'COORDENAÇÃO2',
  16,
  2,
  '07:00',
  '23:59',
  22,
  4,
  '',
  832,
]

export const month4 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'CENTRAL DE ATENDIMENTO E MONITORAÇÃO',
  'GERENCIAMENTO DA INFRA DE MONITORAÇÃO DATACENTER',
  'MEDIA',
  1.84,
  '4. Elaborar, manter, disponibilizar e disseminar documentação, manuais, procedimentos, processos e fluxos operacionais. a. Realizar repasse de conhecimento às equipes CAIXA / terceirizados; b. Preparar e ministrar apresentações relativas às suas atividades sempre que solicitado pela CAIXA; c. Exercitar/Simular contingências, com emissão de pareceres conclusivos quanto à necessidade de correções e aperfeiçoamentos, mantendo o Plano de Contingência sempre atualizado em seu âmbito de atuação. d. Operacionalizar as providências de contingência, em seu âmbito de atuação',
  'COORDENAÇÃO2',
  8,
  1,
  '09:00',
  '18:00',
  22,
  1,
  '',
  338.56,
]

export const month5 = [
  'Suporte à Rede',
  'REDE',
  'REDE DATACENTER',
  'BAIXA',
  1,
  'Acionar suporte do fornecedor, providenciar a abertura de chamados técnicos, executar health check e coletar logs dos equipamentos dentro dos padrões especificados pelos fabricantes',
  'COORDENAÇÃO1',
  1,
  4,
  '00:00',
  '23:59',
  22,
  8,
  '',
  120,
]

export const month6 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'AUTOMAÇÃO',
  'AUTOMAÇÃO DE INFRAESTRUTURA E SERVIÇOS DATACENTER',
  'ALTA',
  3.37,
  'Acompanhar e documentar provas de conceitos de novas tecnologias de mercado. Prospectar inovação nos processos, procedimentos e ferramentas de operações de TI. Definir e documentar padrões a serem seguidos para as soluções de operações de TI.  Automatizar a descoberta de padrões de tendência.  Criar processo de detecção de anomalias.',
  'COORDENAÇÃO3',
  1,
  2,
  '09:00',
  '18:00',
  22,
  0,
  '',
  148.28,
]

export const month7 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'AUTOMAÇÃO',
  'AUTOMAÇÃO DE INFRAESTRUTURA E SERVIÇOS DATACENTER',
  'ALTA',
  3.37,
  'Acompanhar e documentar provas de conceitos de novas tecnologias de mercado. Prospectar inovação nos processos, procedimentos e ferramentas de operações de TI. Definir e documentar padrões a serem seguidos para as soluções de operações de TI. Automatizar a descoberta de padrões de tendência.  Criar processo de detecção de anomalias. (Desenvolvimento)',
  'COORDENAÇÃO3',
  1,
  2,
  '09:00',
  '18:00',
  22,
  0,
  '',
  148.28,
]

export const month8 = [
  'Suporte à Rede',
  'REDE',
  'REDE DATACENTER',
  'MEDIA',
  1.84,
  'Acompanhar fornecedores no tratamento de chamados técnicos para verificação e/ou manutenção do ambiente e para aplicação de correções',
  'COORDENAÇÃO1',
  2,
  2,
  '00:00',
  '23:59',
  22,
  8,
  '',
  220.8,
]

export const month9 = [
  'Suporte à Rede',
  'REDE',
  'ADMINISTRAÇÃO DE SERVIÇO DE REDE',
  'MEDIA',
  1.84,
  'Analisar a integridade de configuração dos serviços em plataforma baixa (sistema operacional Windows). Produzir relatório com a análise de integridade da configuração dos serviços em plataforma baixa, com periodicidade e padrão definidos pela CAIXA. Produzir relatório com a análise de integridade da configuração de integração dos serviços em plataforma baixa, com outras soluções. Produzir relatórios de desempenho dos serviços em plataforma baixa. Produzir relatórios de capacidade dos serviços em plataforma baixa. Atualizar topologias e documentação dos serviços em plataforma baixa.',
  'COORDENAÇÃO1',
  4,
  1,
  '00:00',
  '23:59',
  22,
  8,
  '',
  220.8,
]

export const month10 = [
  'Suporte à Rede',
  'REDE',
  'ADMINISTRAÇÃO DE SERVIÇO DE REDE',
  'MEDIA',
  1.84,
  'Analisar a integridade de configuração dos serviços em plataforma baixa  (sistema operacional Linux). Produzir relatório com a análise de integridade da configuração dos serviços em plataforma baixa, com periodicidade e padrão definidos pela CAIXA. Produzir relatório com a análise de integridade da configuração de integração dos serviços em plataforma baixa, com outras soluções. Produzir relatórios de desempenho dos serviços em plataforma baixa. Produzir relatórios de capacidade dos serviços em plataforma baixa. Atualizar topologias e documentação dos serviços em plataforma baixa.',
  'COORDENAÇÃO1',
  4,
  1,
  '00:00',
  '23:59',
  22,
  8,
  '',
  220.8,
]

export const month11 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'AUTOMAÇÃO',
  'AUTOMAÇÃO DE INFRAESTRUTURA E SERVIÇOS DATACENTER',
  'ALTA',
  3.37,
  'Analisar os dados de múltiplas fontes e arquitetar solução integrada de análise de dados ',
  'COORDENAÇÃO3',
  4,
  2,
  '08:00',
  '18:00',
  10,
  0,
  '',
  269.6,
]

export const month12 = [
  'Suporte, apoio e gestão de ambientes computacionais',
  'AUTOMAÇÃO',
  'AUTOMAÇÃO DE INFRAESTRUTURA E SERVIÇOS DATACENTER',
  'MEDIA',
  1.84,
  'Apoiar  as demais areas da TI na utilização dos ambientes de auto serviço  e esteiras ágeis (Ambientes On premises e Nuvem)',
  'COORDENAÇÃO3',
  1,
  2,
  '08:00',
  '22:00',
  10,
  0,
  'Retificado',
  36.8,
]

//////////////////

export const coordinations = ['Coordenação1', 'Coordenação2', 'Coordenação3']
